### ISSUE TITLE
We are missing a 'No Results Found' message

### ISSUE THREAD

**Issue by danielbyler** [Datawheel/datausa-site#81] opened 2015-12-11 15:11 UTC
We need some kind of 'no results found' message. I even hit enter after searching and it didn't come up. 

![image](https://cloud.githubusercontent.com/assets/3857364/11747144/8b90a02c-9fef-11e5-8624-b62ff2283b25.png)

**Comment by danielbyler** [comment] 2015-12-11 15:13
Figured it out. You do get suggestions when you're a certain amount (maybe 1-2 letters) away from a real result and that part works great. If you violently keep typing incoherent stuff, the system gets confused and offers nothing. This might just be a catch at the end of your matching protocol- hopefully that's all it is.

**Comment by davelandry** [comment] 2015-12-11 21:31
duplicate of #4

**Closed by davelandry** 2015-12-11 21:31 UTC
